# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TESTE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sujeito', models.CharField(max_length=255)),
                ('Predicado', models.CharField(max_length=255)),
                ('Objecto', models.CharField(max_length=255)),
            ],
        ),
    ]
